# [1]. Basics of Linear Algebra

In [1]:
#Create a Vector(vector can be considered as 1D array)
from numpy import array
v = array([1,2,3])
print(v)

[1 2 3]


In [3]:
#Multiplying Vector
from numpy import array
a = array([1,2,3])
print(a)
b = array([1,2,3])
print(b)
c = a*b
print(c)

[1 2 3]
[1 2 3]
[1 4 9]


In [4]:
#Create a Matrix (Matrix can be implemented as 2D array)
from numpy import array
A = array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [6]:
# Matrix Addition
from numpy import array
A = array([[1,2,3],[4,5,6]])
print(A)
B = array([[1,2,3],[4,5,6]])
print(B)
C = A + B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


In [7]:
# Matrix Multiplication or Matrix Dot Product
# C(m,k) = A(m,n) * B(n,k)
from numpy import array
A = array([[1,2],[3,4],[5,6]]) # 3x2 matrix
print(A)
B = array([[1,2],[3,4]]) # 2x2 matrix
print(B)
C = A.dot(B)
print(C) # 3x2 matrix

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]
 [23 34]]


In [8]:
# Transpose a Matrix
from numpy import array
A = array([[1,2],[3,4],[5,6]]) # 3x2 matrix
print(A)
C = A.T
print(C) # 2x3 matrix

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [9]:
# Inverse a Matrix
from numpy import array
from numpy.linalg import inv
A = array([[1.0,2.0],[3.0,4.0]])
print(A)
B = inv(A)
print(B)

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]


# [2]. Linear Algebra in Python

## NumPy N-dimensional Array:

In [12]:
# create array
from numpy import array
l = [1.0,2.0,3.0]
a = array(l)
print(a)
print(a.shape) # define dimension
print(a.dtype) # define data type of array

[1. 2. 3.]
(3,)
float64


## Functions to Create Arrays:

## Empty
The empty() function will create a new array of the specified shape.

In [14]:
# create empty array
from numpy import empty
a = empty([3,3]) # creates an empty 3×3 two-dimensional array.
print(a)

[[0.2298477  0.88346102 0.40824829]
 [0.52474482 0.24078249 0.81649658]
 [0.81964194 0.40189603 0.40824829]]


## Zeros
The zeros() function will create a new array of the specified size with the contents filled with zero values.

In [15]:
# create zeros array
from numpy import zeros
a = zeros([3,5]) # creates a 3×5 zero two-dimensional array.
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Ones 
The ones() function will create a new array of the specified size with the contents filled with one values.

In [16]:
# create ones array
from numpy import ones
a = ones([5]) # creates a 5-element one-dimensional array.
print(a)

[1. 1. 1. 1. 1.]


## Combining Arrays:

## Vertical Stack

In [18]:
# Vertical Stack
from numpy import array
from numpy import vstack
a1 = array([1,2,3]) # 1D array
print(a1)
a2 = array([4,5,6]) # 1D array
print(a2)
a3 = vstack((a1,a2)) # 2D array of dim 2x3
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


## Horizontal Stack

In [20]:
#hstack
from numpy import array
from numpy import hstack
a1 = array([1,2,3])
print(a1)
a2 = array([4,5,6])
print(a2)
a3 = hstack((a1,a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)


## How to Index, Slice and Reshape NumPy Arrays for Machine Learning in Python


## 1) From List to Arrays:

## ~ One-Dimensional List to Array

In [22]:
#one dimensional example
from numpy import array
#list of data
data = [11,22,33,44,55]
#array of data
data = array(data)
print(data)
print(type(data))

[11 22 33 44 55]
<class 'numpy.ndarray'>


## ~ Two-Dimensional List of Lists to Array

In [23]:
from numpy import array
# list of data
data = [[11, 22],
		[33, 44],
		[55, 66]]
# array of data
data = array(data)
print(data)
print(type(data))

[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


## 2)Array Indexing:

## ~ One-Dimensional Indexing

In [24]:
# simple indexing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[0])
print(data[4])

11
55


In [25]:
# Specifying integers too large for the bound of the array will cause an error.
# simple indexing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[5])

IndexError: index 5 is out of bounds for axis 0 with size 5

In [26]:
# One key difference is that you can use negative indexes to retrieve values offset from the end of the array.
    #For example, the index -1 refers to the last item in the array. 
    #The index -2 returns the second last item all the way back to -5 for the first item in the current example.
    
# simple indexing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[-1])
print(data[-5])

55
11


## ~ Two-Dimensional Indexing

In [28]:
# 2d indexing
from numpy import array
# define array
data = array([[11, 22],
              [33, 44],
              [55, 66]])
# index data
print(data[0,0])

11


In [30]:
# If we are interested in all items in the first row, we could leave the second dimension index empty, for example:

# 2d indexing
from numpy import array
# define array
data = array([[11, 22],
              [33, 44],
              [55, 66]])
# index data
print(data[0,])

[11 22]


## 3)Array Slicing:

## ~ One-Dimensional Slicing

In [31]:
# simple slicing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[:]) # access all data in an array dimension by specifying the slice ‘:’ with no indexes.

[11 22 33 44 55]


In [32]:
# simple slicing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[0:1])
#array can be sliced by specifying a slice that starts at index 0 and ends at index 1 
 #(one item before the ‘to’ index).

[11]


In [33]:
# We can also use negative indexes in slices. 
# For example, we can slice the last two items in the list by starting the slice at -2 (the second last item) 
# and not specifying a ‘to’ index; that takes the slice to the end of the dimension.

# simple slicing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[-2:])

[44 55]


## ~ Two-Dimensional Slicing:

### ~~ Split Input and Output Features

In [ ]:
# We can do this by slicing all rows and all columns up to, but before the last column, 
# then separately indexing the last column.

# For the input features, we can select all rows and all columns except the last one by 
# specifying ‘:’ for in the rows index, and :-1 in the columns index.

# X = [:, :-1]

# For the output column, we can select all rows again using ‘:’ and index just the 
# last column by specifying the -1 index.


# y = [:, -1]


In [34]:
# split input and output
from numpy import array
# define array
data = array([[11, 22, 33],
              [44, 55, 66],
              [77, 88, 99]])
# separate data
X, y = data[:, :-1], data[:, -1]
print(X)
print(y)
# Note that X is a 2D array and y is a 1D array.

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


### ~~ Split Train and Test Rows

In [ ]:
# This is a splitting of rows where some portion will be used to train the model and the remaining 
# portion will be used to estimate the skill of the trained model.

# This would involve slicing all columns by specifying ‘:’ in the second dimension index. 
# The training dataset would be all rows from the beginning to the split point.

#dataset
#train = data[:split, :]

# The test dataset would be all rows starting from the split point to the end of the dimension.
# test = data[split:, :]

In [35]:
# split train and test
from numpy import array
# define array
data = array([[11, 22, 33],
              [44, 55, 66],
              [77, 88, 99]])
# separate data
split = 2
train,test = data[:split,:],data[split:,:]
print(train)
print(test)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


## 4)Array Reshaping:
After slicing your data, you may need to reshape it.
For example, some libraries, such as scikit-learn, may require that a one-dimensional array of output variables (y) be shaped as a two-dimensional array with one column and outcomes for each column.

## Data Shape

In [37]:
# array shape
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape) #prints a tuple for the one dimension.

(5,)


In [38]:
# array shape
from numpy import array
# list of data
data = [[11, 22],
        [33, 44],
        [55, 66]]
# array of data
data = array(data)
print(data.shape)

(3, 2)


In [39]:
# array shape
from numpy import array
# list of data
data = [[11, 22],
		[33, 44],
		[55, 66]]
# array of data
data = array(data)
print('Rows: %d' % data.shape[0])
print('Cols: %d' % data.shape[1])

Rows: 3
Cols: 2


## Reshape 1D to 2D Array
It is common to need to reshape a one-dimensional array into a two-dimensional array with one column and multiple arrays.

In [41]:
# reshape 1D array
from numpy import array
from numpy import reshape
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)
# reshape
data = data.reshape((data.shape[0], 1))#the tuple would be the shape of the array as the first dimension (data.shape[0]) and 1 for the second dimension.
print(data.shape)

(5,)
(5, 1)


## Reshape 2D to 3D Array
It is common need to reshape two-dimensional data where each row represents a sequence into a three-dimensional array for algorithms that expect multiple samples of one or more time steps and one or more features. Ex-LSTM RNN

In [42]:
# reshape 2D array
from numpy import array
# list of data
data = [[11, 22],
        [33, 44],
        [55, 66]]
# array of data
data = array(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)

(3, 2)
(3, 2, 1)


# [3]. Vectors for Machine Learning

## Basic Vector Arithmetic:

In [43]:
# create a vector
from numpy import array
v = array([1, 2, 3])
print(v)

[1 2 3]


In [44]:
# add vectors
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a + b
print(c)

[1 2 3]
[1 2 3]
[2 4 6]


In [45]:
# subtract vectors
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([0.5, 0.5, 0.5])
print(b)
c = a - b
print(c)

[1 2 3]
[0.5 0.5 0.5]
[0.5 1.5 2.5]


In [46]:
# multiply vectors
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a * b
print(c)

[1 2 3]
[1 2 3]
[1 4 9]


In [47]:
# divide vectors
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a / b
print(c)

[1 2 3]
[1 2 3]
[1. 1. 1.]


In [48]:
# dot product vectors
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a.dot(b)
print(c)

[1 2 3]
[1 2 3]
14


In [49]:
# vector-scalar multiplication
from numpy import array
a = array([1, 2, 3])
print(a)
s = 0.5
print(s)
c = s * a
print(c)

[1 2 3]
0.5
[0.5 1.  1.5]


## Vector Norms in Machine Learning:

## 1). Vector Norm

- Calculating the size or length of a vector is often required either directly or as part of a broader vector or vector-matrix operation.
- The length of the vector is referred to as the vector norm or the vector’s magnitude.
- The length of a vector is a nonnegative number that describes the extent of the vector in space, and is sometimes referred to as the vector’s magnitude or the norm.
- The length of the vector is always a positive number, except for a vector of all zero values. It is calculated using some measure that summarizes the distance of the vector from the origin of the vector space. For example, the origin of a vector space for a vector with 3 elements is (0, 0, 0).

## 2). Vector L1 Norm

In [50]:
# l1 norm of a vector
# The L1 norm that is calculated as the sum of the absolute values of the vector.
from numpy import array
from numpy.linalg import norm
a = array([1, 2, 3])
print(a)
l1 = norm(a, 1)#uses the norm() function with a parameter to specify the norm order, in this case 1.
print(l1)

[1 2 3]
6.0


## 3). Vector L2 Norm

In [51]:
# l2 norm of a vector
# The L2 norm that is calculated as the square root of the sum of the squared vector values.
from numpy import array
from numpy.linalg import norm
a = array([1, 2, 3])
print(a)
l2 = norm(a) #uses default parameter
print(l2)

[1 2 3]
3.7416573867739413


## 4). Vector Max Norm

In [52]:
# max norm of a vector
# The max norm that is calculated as the maximum vector values.
from numpy import inf
from numpy import array
from numpy.linalg import norm
a = array([1, 2, 3])
print(a)
maxnorm = norm(a, inf)
print(maxnorm)

[1 2 3]
3.0


# [4]. Matrix Types in Linear Algebra for Machine Learning

In [53]:
# triangular matrices
from numpy import array
from numpy import tril
from numpy import triu
M = array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
print(M)
lower = tril(M)
print(lower)
upper = triu(M)
print(upper)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 0 0]
 [1 2 0]
 [1 2 3]]
[[1 2 3]
 [0 2 3]
 [0 0 3]]


In [54]:
# diagonal matrix
from numpy import array
from numpy import diag
M = array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
print(M)
# extract diagonal vector
d = diag(M)
print(d)
# create diagonal matrix from vector
D = diag(d)
print(D)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [55]:
# identity matrix
from numpy import identity
I = identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [56]:
# orthogonal matrix
from numpy import array
from numpy.linalg import inv
Q = array([[1, 0], [0, -1]])
print(Q)
# inverse equivalence
V = inv(Q)
print(Q.T)
print(V)
# identity equivalence
I = Q.dot(Q.T)
print(I)

[[ 1  0]
 [ 0 -1]]
[[ 1  0]
 [ 0 -1]]
[[ 1.  0.]
 [-0. -1.]]
[[1 0]
 [0 1]]


# [5]. Matrix Factorization/Decomposition & Eigen Decomposition of a Matrix

## Matrix Factorization/Decomposition:

## LU Matrix Decomposition

In [10]:
# Matrix decomposition or Matrix factorization for Square Matrix
# LUP decomposition or LU decomposition with partial pivoting.
from numpy import array
from scipy.linalg import lu
# define a square matrix
A = array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
# LU Decomposition
P,L,U = lu(A)
print(P)
print(L)
print(U)
# reconstruct
B = P.dot(L).dot(U)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[7.00000000e+00 8.00000000e+00 9.00000000e+00]
 [0.00000000e+00 8.57142857e-01 1.71428571e+00]
 [0.00000000e+00 0.00000000e+00 1.11022302e-16]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## QR Matrix Decomposition

In [57]:
# QR decomposition
from numpy import array
from numpy.linalg import qr
# define a 3x2 matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# QR decomposition
Q, R = qr(A, 'complete')
print(Q)
print(R)
# reconstruct
B = Q.dot(R)
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


## Cholesky Decomposition

In [58]:
# Cholesky decomposition
from numpy import array
from numpy.linalg import cholesky
# define a 3x3 matrix
A = array([[2, 1, 1], [1, 2, 1], [1, 1, 2]])
print(A)
# Cholesky decomposition
L = cholesky(A)
print(L)
# reconstruct
B = L.dot(L.T)
print(B)

[[2 1 1]
 [1 2 1]
 [1 1 2]]
[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


## Singular-Value Decomposition

In [11]:
# Singular-Value Decomposition for Matrix factorization or SVD.
    # The Singular-Value Decomposition, or SVD for short, is a matrix decomposition method 
    # for reducing a matrix to its constituent parts in order to make certain subsequent 
    # matrix calculations simpler.
#Singular-Value Decomposition
from numpy import array
from scipy.linalg import svd
A = array([[1,2],[3,4],[5,6]])
print(A)
# SVD
U,s,V = svd(A)
print(U)
print(s)
print(V)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


## Eigen Decomposition:

This tutorial is divided into 5 parts; they are:

1. Eigendecomposition of a Matrix
2. Eigenvectors and Eigenvalues
3. Calculation of Eigendecomposition
4. Confirm an Eigenvector and Eigenvalue
5. Reconstruct Original Matrix

## Calculation of Eigendecomposition

In [62]:
# eigendecomposition
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])
print(A)
# calculate eigendecomposition
values, vectors = eig(A)
print(values)
print(vectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


## Confirm an Eigenvector and Eigenvalue

In [60]:
# confirm eigenvector
# A vector is an eigenvector of a matrix if it satisfies the following equation.
# A . v = lambda . v
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])
# calculate eigendecomposition
values, vectors = eig(A)
# confirm first eigenvector
B = A.dot(vectors[:, 0])
print(B)
C = vectors[:, 0] * values[0]
print(C)

[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]


## Reconstruct Original Matrix

In [63]:
# reconstruct matrix
# The parent matrix can be shown to be a product of the eigenvectors and eigenvalues.
# A = Q . diag(V) . Q^-1
from numpy import diag
from numpy import dot
from numpy.linalg import inv
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])
print(A)
# calculate eigenvectors and eigenvalues
values, vectors = eig(A)
# create matrix from eigenvectors
Q = vectors
# create inverse of eigenvectors matrix
R = inv(Q)
# create diagonal matrix from eigenvalues
L = diag(values)
# reconstruct the original matrix
B = Q.dot(L).dot(R)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
